language: python

sudo: false

python:
  - '3.5'
  - '3.6'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda config --add channels gwforg

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip=9.0.1 conda-build=3.0.15 anaconda-client=1.6.0
  - pip install coveralls
  - conda build --python $TRAVIS_PYTHON_VERSION conda/
  - conda install --use-local gwf

script: make test

after_success:
  - coveralls
  - chmod +x ./deploy_conda.sh

deploy:
  - provider: pypi
    username: dansondergaard
    password:
      secure: xoA/xtueC8420iENzNrhIfo+FyxAVG5DhesUa6AxGk8qvR7/DqVU5Rsuj0r0f+l5LwoXvBLCisl2rAbQu+LjZ2jPU2UKKsae0P6V9JInHFf5i2Y7VeGkUIrB5vsWvyPLbTCYUqJwtxVlvGI$46houxpM51gf+lQqP74abIjMZ8O7EycOXprgVWDCuLAlp2tS0yPPmiAiAa5LKiLNkhSaBbHB3Dx2y+oDbtx4OzECUr1LpaH1GeU2ztWjC9kr8ySKlNXTr9C+EZ2BZhRMZyoI/eNo1uVmU6I5Nyvyazf2017wF+oHMY83b6AwKsIpSRa5De/cI8+Ggzca8XHa1j3Na2b4aCKZ3Sur0CLxeHgw+7aLWUkj8v292IhEQl6bU0AU3tGXIPKFuU3UB+e/sHprVYtkBxtYVdnsoJzgdO/lPMiW4pVwV3EOswCO80ldRHwD8ayk901u/9BeeBZ9Xe5OFXA6ESsMzBGOufttJBQ5YkAyp/YYVtsWOPS1C087n5VQ5pZLZ8AWmLvnWgJ2T0IddtSMH+5HxojfbPlAaGaH1wdQV4jCvRwuDPPgtN0Jg2xXGPPBbpUdKRNEmMGSOHwXyzgsZ7XJR2VsfKUcnpKgvAwmsodOi1mcdCwWIL1a08KjkXElPOA4G05N8AP7kCUKg4/Jatd/XBq+2NdxkdDLJOys=
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
  - provider: script
    script: ./deploy_conda.sh
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
